name: Release new version to NPMJS
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - name: npm versioning
      - uses: pengyanb/npm-versioning-action@v1
        with:
          release-branch: "master" 
          package-json-path: "./package.json"
          update-version: true
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: npm publish
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm install && npm run publish --tag ${{ steps.npmVersioning.outputs.tag }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
